### ISSUE TITLE
problem running example without swift lint

### ISSUE THREAD

**Issue by ammoqq** [svtek/VideoSplashKit#16]
I simply downloaded the library to see how it looks with the airplane video, but got this message:

myderivedDatalocation/DerivedData/VideoSplash-hewgngxkasswrscufpaujewroedd/Build/Intermediates/VideoSplash.build/Debug-iphoneos/VideoSplash.build/Script-C3CEBF9F1BCCA22200CB209E.sh: line 2: /usr/local/bin/swiftlint: No such file or directory

I simply downloaded a zip, unzipped it and opened xcodeproj.

Any idea how to simply look check how this library looks like running on an iphone ?

**Comment by OmarCloud20** [comment]
I wonder if you had a resolution for this issue as I was not able to run the app for the similar issue you had. You have closed the issue, does that mean you have a solution for this issue.? 
Thanks.

**Comment by toygar-zzz** [comment]
you're right, I'm fixing it @FracAppz @ammoqq

**Comment by ammoqq** [comment]
Yeah i fixed it, you need to bo into xcode and Then go to run scripts section and simply remove the line /usr/local/bin/swiftlint

**Comment by toygar-zzz** [comment]
You can remove if you want to run or, If it can resolve the problem established swiftlint. https://github.com/realm/SwiftLint  (sorry for my english) :)
