### ISSUE TITLE
Swift 2.0 Support

### ISSUE THREAD

**Issue by iliraga** [svtek/VideoSplashKit#3]
Hello
What are the plans for supporting Swift 2.0 in the future? They changed quite a lot in the new specification, and this framework makes it impossible to build an app in iOS 9 and XCode 7

**Comment by ZacharyKhan** [comment]
I agree, Swift 2.0 support is imperative. I would like to fork the repo and try to update it to Xcode 7 and Swift 2.0

**Comment by toygar-zzz** [comment]
Updated project support swift 2.0 (V.1.0.5)
