### ISSUE TITLE
Support Swift 3

### ISSUE THREAD

**Issue by sovannarithsok** [svtek/VideoSplashKit#33]
Please update it to support swift 3. Thanks

**Comment by balazsnemeth** [comment]
👍

**Comment by mruvim** [comment]
[Pull request](https://github.com/movielala/VideoSplashKit/pull/35) submitted

**Comment by freegyp** [comment]
After pod install, it still says "The target “VideoSplashKit” contains source code developed with an earlier version of Swift."

**Comment by mruvim** [comment]
@freegyp pull request was not merged

**Comment by freegyp** [comment]
When are you going to merge?

**Comment by mruvim** [comment]
@freegyp i'm not the repo owner, cannot merge it

**Comment by surayashivji** [comment]
Any updates on this?

**Comment by ahmedOmran** [comment]
Any support for swift 3 ?

**Comment by hrsalehi** [comment]
same here. please update support swift 3.0

**Comment by piv199** [comment]
Any swift 3.0 analogue?

**Comment by rmvz3** [comment]
Still no Swift 3?

I think I'll be using https://github.com/hoangtam101/VideoSplashKit in the meantime.

**Comment by Belalm** [comment]
can u support swift 3 please

**Comment by hemangshah** [comment]
@rmvz3, how to install (https://github.com/hoangtam101/VideoSplashKit) with Cocoapods?

**Comment by hemangshah** [comment]
@okaris, why this is closed without any reply?
If you can't maintain this library then give access to me and I can handle this repo.

**Comment by okaris** [comment]
Seift 3 support has been added. PR has been merged and a new version is released.

**Comment by sahin** [comment]
@hemangshah emailing you about your offer?
